"""Add S3 shares table

Revision ID: 3a4878198306
Revises: af19d45361bc
Create Date: 2025-10-28 19:54:28.352589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4878198306'
down_revision = 'af19d45361bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_shares',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('share_code', sa.String(length=32), nullable=False),
        sa.Column('share_token', sa.String(length=64), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_type', sa.String(length=100), nullable=False),
        sa.Column('file_extension', sa.String(length=10), nullable=False),
        sa.Column('s3_url', sa.String(length=1000), nullable=False),
        sa.Column('public_url', sa.String(length=1000), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('download_count', sa.Integer(), nullable=False),
        sa.Column('max_downloads', sa.Integer(), nullable=True),
        sa.Column('uploader_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_shares_share_code'), 's3_shares', ['share_code'], unique=True)
    op.create_index(op.f('ix_s3_shares_share_token'), 's3_shares', ['share_token'], unique=True)
    op.create_index(op.f('ix_s3_shares_uploader_id'), 's3_shares', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s3_shares_uploader_id'), table_name='s3_shares')
    op.drop_index(op.f('ix_s3_shares_share_token'), table_name='s3_shares')
    op.drop_index(op.f('ix_s3_shares_share_code'), table_name='s3_shares')
    op.drop_table('s3_shares')
    # ### end Alembic commands ###
