"""add_2fa_fields_to_users_table

Revision ID: af19d45361bc
Revises: fa40565fe928
Create Date: 2025-10-25 16:01:28.681208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af19d45361bc'
down_revision = 'fa40565fe928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('backup_codes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('two_factor_setup_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_setup_date')
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
