from setuptools import setup, find_packages

setup(
    name="enterprise-wiki",
    version="1.0.0",
    description="A comprehensive enterprise knowledge base and wiki system",
    author="Enterprise Team",
    author_email="admin@company.com",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        "Flask==2.3.3",
        "Flask-SQLAlchemy==3.0.5",
        "Flask-Login==0.6.3",
        "Flask-WTF==1.1.1",
        "Flask-Mail==0.9.1",
        "Flask-Migrate==4.0.5",
        "Werkzeug==2.3.7",
        "WTForms==3.0.1",
        "Markdown==3.5.1",
        "Pygments==2.16.1",
        "Bleach==6.0.0",
        "python-dotenv==1.0.0",
        "bcrypt==4.0.1",
        "cryptography==41.0.4",
        "Pillow==10.0.1",
        "Whoosh==2.7.4",
        "redis==5.0.0",
        "celery==5.3.2",
        "unidecode==1.3.6",
        "itsdangerous==2.1.2",
    ],
    extras_require={
        "dev": [
            "pytest==7.4.2",
            "pytest-flask==1.2.0",
            "pytest-cov==4.1.0",
            "black==23.7.0",
            "flake8==6.0.0",
            "isort==5.12.0",
        ],
        "production": [
            "gunicorn==21.2.0",
            "supervisor==4.2.5",
        ]
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Framework :: Flask",
    ],
    python_requires=">=3.8",
)